### ISSUE TITLE
Can't call register from paymentpage

### ISSUE THREAD

**Issue by pitsanubomb** [goragod/ecommerce#1]
https://ecommerce.goragod.com/modules/payment/newregister.php

Can't regist but refresh can access page

**Comment by goragodwiriya** [comment]
do not call direct link

**Comment by pitsanubomb** [comment]
> do not call direct link

I don't call direct but it's error from you web page

**Comment by goragodwiriya** [comment]
Show your error

**Comment by pitsanubomb** [comment]
![image](https://user-images.githubusercontent.com/13832342/89514972-be264480-d800-11ea-915d-00849d200638.png)

https://ecommerce.goragod.com/index.php?module=payment-login&ret=product

**Comment by goragodwiriya** [comment]
![image](https://user-images.githubusercontent.com/2264492/89530476-bffc0200-d818-11ea-9c26-0a6732fe7cb6.png)
Try disabling your Chrome extension.

**Comment by pitsanubomb** [comment]
Ok.Thank it's work for no extension.
